"""adding question_id column to Score table

Revision ID: 88aee6f8e729
Revises: fb853d316b5d
Create Date: 2021-05-16 15:59:55.876516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88aee6f8e729'
down_revision = 'fb853d316b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('question_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'question_id')
    # ### end Alembic commands ###
